sc_licence:
    resource: "@SCLicenceBundle/Resources/config/routing.yml"
    prefix:   /

sc_activite:
    resource: "@SCActiviteBundle/Resources/config/routing.yml"
    prefix:   /activite

sc_user:
    pattern:   /user
    defaults:  { _controller: SCUserBundle:Default:index }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    pattern:   /login
    defaults:  { _controller: SCUserBundle:Security:login }

login_check:
    pattern:   user/login_check

logout:
    pattern:   user/logout  
