sc_activite:
    resource: "@SCActiviteBundle/Resources/config/routing.yml"
    prefix:   /activite

sc_user:
    resource: "@SCUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
