<?php

namespace SC\ActiviteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use SC\ActiviteBundle\Entity\Saison;
use SC\ActiviteBundle\Entity\SaisonRepository;
/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRepository extends EntityRepository
{
    public function getActiviteSaison($saison) {
      return $this->createQueryBuilder('a')
                    ->leftJoin('a.id','activites_saisons')
                    ->addSelect('activites_saisons')
                    ->where('a.annee = :annee')
                    ->setParameter('annee', $saison);
    

              
    }               

}

