<?php

namespace SC\ActiviteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionActiviteRepository extends EntityRepository
{
}
