<?php

namespace SC\ActiviteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use SC\UserBundle\Entity\Enfant;
/**
 * InscriptionActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionActiviteRepository extends EntityRepository
{
    public function est_Inscrit($inscriptionActivite) 
    {
       $qb= $this->createQueryBuilder('i')
         ->where('i.prenomEnfant = :prenomEnfant')
         ->setParameter('prenomEnfant', $inscriptionActivite  -> getPrenomEnfant() )
         -> andWhere  ('i.nomEnfant = :nomEnfant')
         ->setParameter('nomEnfant', $inscriptionActivite -> getNomEnfant() )
         ->andwhere('i.saison = :annee')
         ->setParameter('annee', $inscriptionActivite -> getSaison() -> getAnnee() )
         ->andwhere('i.email = :email')
         ->setParameter('email', $inscriptionActivite -> getEmail() )
         ->andwhere('i.activite = :id')
         ->setParameter('id', $inscriptionActivite -> getActivite() ->getId()  );
        return $qb->getQuery()->getResult();

    }
    public function ListeEnfantsinscrits($email)
    {
        $qb= $this->createQueryBuilder('i')
         ->where('i.email = :email')
         ->setParameter('email', $email);
        
        return $qb->getQuery()->getResult();
        
    }

    
    
}
