<?php

namespace SC\ActiviteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionSortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionSortieRepository extends EntityRepository
{
    public function confirmationParticipation($id,$dateSortie,$lieu,$nomEnfant,$prenomEnfant,$year,$email) {
      $query = $this->_em->createQuery('UPDATE SCActiviteBundle:InscriptionSortie a SET a.participation = :takePart where a.idActivite = :id AND a.saison = :year AND a.dateSortie = :date AND a.lieu = :lieu and a.nomEnfant = :nom AND a.prenomEnfant = :prenom AND a.emailParent = :email')
                       ->setParameter('takePart', 1)
                       ->setParameter('id', $id)
                       ->setParameter('year', $year)
                       ->setParameter('date', $dateSortie)
                       ->setParameter('lieu', $lieu)
                       ->setParameter('nom', $nomEnfant)
                       ->setParameter('prenom', $prenomEnfant)
                       ->setParameter('email', $email);

       $query->execute();
    }
    public function modifSortie($id,$dateSortieNew,$lieuNew,$year,$dateSortie,$lieu) {
      $query = $this->_em->createQuery('UPDATE SCActiviteBundle:InscriptionSortie a SET a.lieu =:nomLieuNew , a.dateSortie = :dateSortieNew where a.idActivite = :id AND a.saison = :year AND a.dateSortie = :date AND a.lieu = :lieu')
                       ->setParameter('id', $id)
                       ->setParameter('year', $year)
                       ->setParameter('date', $dateSortie)
                       ->setParameter('lieu', $lieu)
                       ->setParameter('dateSortieNew', $dateSortieNew)
                       ->setParameter('nomLieuNew', $lieuNew); 


       $query->execute();
           
    }    
}
