<?php

namespace SC\ActiviteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonRepository extends EntityRepository
{

      public function getActiviteSaison($saison) {
      return $this->createQueryBuilder('a')
                    ->where('a.annee = :annee')
                    ->setParameter('annee', $saison);
    

              
    }   
    
    public function getActiviteSaison2($saison) {
      return $this->createQueryBuilder('a')
                    ->leftJoin('a.activites', 'app')
                        ->addSelect('app')
                            ->where('a.annee = :annee')
                                ->setParameter('annee', $saison);
    

              
    }      
}
