<?php

namespace SC\ActiviteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortieRepository extends EntityRepository
{  
    public function getPublishedQueryBuilder($act)
    {
    return $this->createQueryBuilder('a')
      ->where('a.activite = :idAct')
      ->setParameter('idAct', $act);
    }
}
