<?php

namespace SC\ParticipationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionSortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionSortieRepository extends EntityRepository
{
}
