<?php

namespace SC\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdhesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdhesionRepository extends EntityRepository
{
}
