<?php

namespace SC\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantRepository extends EntityRepository
{

  public function getPublishedQueryBuilder($parent)
  {
    return $this->createQueryBuilder('a')
      ->where('a.userParent = :parents')
      ->setParameter('parents', $parent);
  }
  
  
  public function getEnfant($email) 
  {
      return $this -> createQueryBuilder('e')
        ->where('e.userParent = :email')
        ->setParameter('email', $email);
      
  }
  
  public function getEnfantId($email,$id,$year) {
        
    $qb = $this->_em->createQuery('SELECT a.nomEnfant , a.prenomEnfant from SCUserBundle:Enfant a , SCActiviteBundle:InscriptionActivite b where a.nomEnfant = b.nomEnfant and a.prenomEnfant = b.prenomEnfant and a.userParent = b.email and b.saison = :annee and b.activite = :activite and b.email = :email ')
                        ->setParameter('activite', $id)
                        ->setParameter('annee', $year)    
                        ->setParameter('email', $email);
    return $qb->getResult();
  }

}
