<?php

namespace SC\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantRepository extends EntityRepository
{
    
    public function getEnfant($email)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.userParent = :email')
	   ->setParameter('email', $email);
        return $qb;
    } 
}
