sc_user_homepage:
    path:     /
    defaults: { _controller: SCUserBundle:Default:index }

sc_user_compte:
    path:     /monCompte
    defaults: { _controller: SCUserBundle:Security:compte }


sc_user_register:
    path:     /register
    defaults: { _controller: SCUserBundle:Security:register }
   
sc_user_ajouter:
    path:     /ajouterUser
    defaults: { _controller: SCUserBundle:Security:ajouter }        
        
sc_enfant_ajouter:
    path:     /ajoutEnfant
    defaults: { _controller: SCUserBundle:Enfant:ajouter }
    
sc_admin_homepage:
    path:     /admin
    defaults: { _controller: SCUserBundle:Admin:index }
    
sc_admin_listUsersInactif:
    path:     /admin/listUsersInactif
    defaults: { _controller: SCUserBundle:Admin:listUsersInactif }

sc_admin_activerCompte:
    path:     /admin/activationCompte/{email}
    defaults: { _controller: SCUserBundle:Admin:activerCompte }
    requirements : 
        email : "[^/]+"

sc_admin_supprimerCompte:
    path:     /admin/suppressionCompte/{email}
    defaults: { _controller: SCUserBundle:Admin:supprimerCompte }
    requirements : 
        email : "[^/]+"
        
sc_admin_listNoAdmin:
    path:     /admin/listNoAdmin
    defaults: { _controller: SCUserBundle:Admin:listNoAdmin }
    
    
sc_admin_activerAdmin:
    path:     /admin/activationAdmin/{email}
    defaults: { _controller: SCUserBundle:Admin:activerAdmin }
    requirements : 
        email : "[^/]+"
        
sc_admin_gestionCompte:
    path:     /admin/gestionCompte/{email}
    defaults: { _controller: SCUserBundle:Admin:gestionCompte }
    requirements : 
        email : "[^/]+"      
        
        
sc_admin_ajoutMontant:
    path:     /admin/ajoutMontant/{email}
    defaults: { _controller: SCUserBundle:Admin:ajoutMontant }
    requirements : 
         email : "[^/]+"  
         


sc_admin_gestionEnfant:
    path:     /admin/gestionCompte/gestionEnfant/{email}
    defaults: { _controller: SCUserBundle:Admin:gestionEnfant }
    requirements : 
        email : "[^/]+" 
        

sc_admin_activerlicence:
    path:     /admin/gestionCompte/gestionEnfant/{email}/{prenom}/{nom}/{annee}/{id}
    defaults: { _controller: SCUserBundle:Admin:activerLicence }
    requirements : 
        email : "[^/]+" 
        prenom : "[^/]+"
        nom : "[^/]+"
        annee : "[^/]+"
        id : \d+
    
    

         
sc_admin_ajoutRemise:
    path:     /admin/ajoutRemise/{email}
    defaults: { _controller: SCUserBundle:Admin:ajoutRemise }
    requirements : 
         email : "[^/]+"  
         
         
         
sc_admin_adherer:
    path:     /admin/adhesion/{email}
    defaults: { _controller: SCUserBundle:Admin:adherer }
    requirements : 
         email : "[^/]+"  

sc_activite_voirActivite:
    path:      /voirActivite
    defaults: {_controller:SCActiviteBundle:InscriptionSortie:voirActivite }
    requirements: