sc_user_homepage:
    path:     /
    defaults: { _controller: SCUserBundle:Default:index }

sc_user_compte:
    path:     /monCompte
    defaults: { _controller: SCUserBundle:Security:compte }
    
sc_user_compteEnfant:
    path:     /monCompteEnfant
    defaults: { _controller: SCUserBundle:Security:compteEnfant }
    
sc_user_choixModalite:
    path:     /choixModalite
    defaults: { _controller: SCUserBundle:Security:choixModalite }
    
sc_user_paramCompte:
    path:     /parametreCompte
    defaults: { _controller: SCUserBundle:Security:paramCompte }


sc_user_register:
    path:     /register
    defaults: { _controller: SCUserBundle:Security:register }
   
sc_user_ajouter:
    path:     /ajouterUser
    defaults: { _controller: SCUserBundle:Security:ajouter }        
        
sc_enfant_ajouter:
    path:     /ajoutEnfant
    defaults: { _controller: SCUserBundle:Enfant:ajouter }
    
sc_admin_homepage:
    path:     /admin
    defaults: { _controller: SCUserBundle:Admin:index }
    
sc_admin_listUsersInactif:
    path:     /admin/listUsersInactif
    defaults: { _controller: SCUserBundle:Admin:listUsersInactif }

sc_admin_activerCompte:
    path:     /admin/activationCompte/{email}
    defaults: { _controller: SCUserBundle:Admin:activerCompte }
    requirements : 
        email : "[^/]+"

sc_admin_supprimerCompte:
    path:     /admin/suppressionCompte/{email}
    defaults: { _controller: SCUserBundle:Admin:supprimerCompte }
    requirements : 
        email : "[^/]+"
        
sc_admin_listNoAdmin:
    path:     /admin/listNoAdmin
    defaults: { _controller: SCUserBundle:Admin:listNoAdmin }
    
    
sc_admin_activerAdmin:
    path:     /admin/activationAdmin/{email}
    defaults: { _controller: SCUserBundle:Admin:activerAdmin }
    requirements : 
        email : "[^/]+"
        
sc_admin_gestionCompte:
    path:     /admin/gestionCompte/{email}
    defaults: { _controller: SCUserBundle:Admin:gestionCompte }
    requirements : 
        email : "[^/]+"      
        
        
sc_admin_ajoutMontant:
    path:     /admin/ajoutMontant/{email}
    defaults: { _controller: SCUserBundle:Admin:ajoutMontant }
    requirements : 
         email : "[^/]+"  
         


sc_admin_gestionEnfant:
    path:     /admin/gestionCompte/gestionEnfant/{email}
    defaults: { _controller: SCUserBundle:Admin:gestionEnfant }
    requirements : 
        email : "[^/]+" 
        


         
sc_admin_ajoutRemise:
    path:     /admin/ajoutRemise/{email}
    defaults: { _controller: SCUserBundle:Admin:ajoutRemise }
    requirements : 
         email : "[^/]+"  
         
         
         
sc_admin_adherer:
    path:     /admin/adhesion/{email}
    defaults: { _controller: SCUserBundle:Admin:adherer }
    requirements : 
         email : "[^/]+"  


sc_activite_voirActivite:
    path:      /voirActivite
    defaults: {_controller:SCActiviteBundle:InscriptionSortie:voirActivite }
    requirements:

sc_admin_changePassword:
    path:     /admin/changePassword/{email}
    defaults: { _controller: SCUserBundle:Admin:changePassword }
    requirements : 
         email : "[^/]+"

sc_inscription_getChoix:
    path:      /getChoix/{id}/{dateSortie}/{lieu}/{nomEnfant}/{prenomEnfant}
    defaults:  { _controller: SCActiviteBundle:InscriptionSortie:getChoix }
    requirements:
        id: \d+
sc_inscription_validation:
    path:      /validation/{id}/{dateSortie}/{nomEnfant}/{prenomEnfant}
    defaults:  { _controller: SCActiviteBundle:InscriptionSortie:validation }
    requirements:
        id: \d+
sc_inscription_annulation:
    path:      /annulation/{id}/{dateSortie}/{nomEnfant}/{prenomEnfant}
    defaults:  { _controller: SCActiviteBundle:InscriptionSortie:annulation }
    requirements:
        id: \d+        

sc_activite_listeEnfantsInscrits:
    path:      /moncompte/mesinscriptions
    defaults:  { _controller: SCActiviteBundle:InscriptionActivite:viewInscriActivite }
    
    
    
sc_admin_Tresorerie:
    path:     /admin/tresorerie
    defaults: { _controller: SCUserBundle:Admin:tresorerie }


sc_affecter_groupe:
    path:   /admin/gestionCompte/gestionEnfant/groupe/{id}/{email}/{prenomEnfant}/{nomEnfant}
    defaults: { _controller: SCUserBundle:Admin:affecterGroupe }
    requirements:
        id: \d+ 
        email: "[^/]+"
        prenomEnfant: "[^/]+"
        nomEnfant: "[^/]+"
 

sc_niveauSki_homepage:
    path:     /admin/niveauSki/{page}
    defaults: { _controller: SCUserBundle:NiveauSki:index, page: 1 }    
    requirements:
        page: \d* 

sc_niveauSki_view:
    path:      /admin/niveauSki/view/{niveau}
    defaults:  { _controller: SCUserBundle:NiveauSki:view }
    requirements:
        typeLicence : "[^/]+"
sc_niveauSki_add:
    path:      /admin/niveauSki/add
    defaults:  { _controller: SCUserBundle:NiveauSki:add }
sc_niveauSki_edit:
    path:      /admin/niveauSki/edit/{niveau}
    defaults:  { _controller: SCUserBundle:NiveauSki:edit}
    requirements:
        typeLicence : "[^/]+"

sc_contact:
    path: /contact
    defaults:  { _controller: SCUserBundle:Admin:contact}