sc_user_homepage:
    path:     /
    defaults: { _controller: SCUserBundle:Default:index }

sc_user_compte:
    path:     /monCompte
    defaults: { _controller: SCUserBundle:Security:compte }


sc_user_register:
    path:     /register
    defaults: { _controller: SCUserBundle:Security:register }
   
sc_user_ajouter:
    path:     /ajouterUser
    defaults: { _controller: SCUserBundle:Security:ajouter }        
        
sc_enfant_ajouter:
    path:     /ajoutEnfant
    defaults: { _controller: SCUserBundle:Enfant:ajouter }
    
sc_admin_homepage:
    path:     /admin
    defaults: { _controller: SCUserBundle:Admin:index }
    
sc_admin_listUsersInactif:
    path:     /admin/listUsersInactif
    defaults: { _controller: SCUserBundle:Admin:listUsersInactif }

sc_admin_activerCompte:
    path:     /admin/activationCompte/{email}
    defaults: { _controller: SCUserBundle:Admin:activerCompte }
    requirements : 
        email : "[^/]+"
        
        
sc_admin_listNoAdmin:
    path:     /admin/listNoAdmin
    defaults: { _controller: SCUserBundle:Admin:listNoAdmin }
    
    
sc_admin_activerAdmin:
    path:     /admin/activationAdmin/{email}
    defaults: { _controller: SCUserBundle:Admin:activerAdmin }
    requirements : 
        email : "[^/]+"