# src/SC/ActiviteBundle/Resources/config/routing.yml

sc_activite_homepage:
    path:     /{page}
    defaults: { _controller: SCActiviteBundle:Activite:index, page: 1 }    
    requirements:
        page: \d* 

sc_activite_view:
    path:      /{id}
    defaults:  { _controller: SCActiviteBundle:Activite:view }
    requirements:
        id: \d+
sc_activite_add:
    path:      /add
    defaults:  { _controller: SCActiviteBundle:Activite:add }
sc_activite_edit:
    path:      /edit/{id}
    defaults:  { _controller: SCActiviteBundle:Activite:edit }
    requirements:
        id: \d+
sc_activite_delete:
    path:      /delete/{id}
    defaults:  { _controller: SCActiviteBundle:Activite:delete }
    requirements:
        id: \d+ 
