# src/SC/ActiviteBundle/Resources/config/routing.yml

sc_activite_homepage:
    path:     /{page}
    defaults: { _controller: SCActiviteBundle:Activite:index, page: 1 }    
    requirements:
        page: \d* 

sc_activite_view:
    path:      /view/{id}
    defaults:  { _controller: SCActiviteBundle:Activite:view }
    requirements:
        id: \d+
sc_activite_add:
    path:      /add
    defaults:  { _controller: SCActiviteBundle:Activite:add }
sc_activite_edit:
    path:      /edit/{id}
    defaults:  { _controller: SCActiviteBundle:Activite:edit }
    requirements:
        id: \d+
sc_activite_delete:
    path:      /delete/{id}
    defaults:  { _controller: SCActiviteBundle:Activite:delete }
    requirements:
        id: \d+ 
        
sc_activite_ajoutSortie:
    path:      /ajoutSortie/{id}
    defaults:  { _controller: SCActiviteBundle:Sortie:ajoutSortie }
    requirements:
        id: \d+
        
sc_activite_voirSortie:
    path:      /voirSortie/{id}
    defaults:  { _controller: SCActiviteBundle:Sortie:voirSortie }
    requirements:
        id: \d+ 
        
sc_activite_deleteSortie:
    path:      /deleteSortie/{id}
    defaults:  { _controller: SCActiviteBundle:Sortie:deleteSortie}
    requirements:
        id: \d+
        
sc_activite_addStage:
    path:      /addStage/{id}
    defaults:  { _controller: SCActiviteBundle:Stage:add }
    requirements:
        id: \d+
        
sc_activite_viewStage:
    path:      /viewStage/{id}
    defaults:  { _controller: SCActiviteBundle:Stage:view }
    requirements:
        id: \d+ 
        
sc_activite_deleteStage:
    path:      /deleteStage/{id}/{debutStage}/{finStage}
    defaults:  { _controller: SCActiviteBundle:Sortie:delete}
    requirements:
        id: \d+
        debutStage: \w+
        finStage: \w+
