# src/SC/ActiviteBundle/Resources/config/routing.yml

sc_activite_homepage:
    path:     /{page}
    defaults: { _controller: SCActiviteBundle:Activite:index, page: 1 }    
    requirements:
        page: \d* 

sc_activite_view:
    path:      /view/{id}
    defaults:  { _controller: SCActiviteBundle:Activite:view }
    requirements:
        id: \d+
sc_activite_add:
    path:      /add
    defaults:  { _controller: SCActiviteBundle:Activite:add }
sc_activite_edit:
    path:      /edit/{id}
    defaults:  { _controller: SCActiviteBundle:Activite:edit }
    requirements:
        id: \d+
sc_activite_delete:
    path:      /delete/{id}
    defaults:  { _controller: SCActiviteBundle:Activite:delete }
    requirements:
        id: \d+ 
        
sc_activite_ajoutSortie:
    path:      /ajoutSortie/{id}
    defaults:  { _controller: SCActiviteBundle:Sortie:ajoutSortie }
    requirements:
        id: \d+
        
sc_activite_voirSortie:
    path:      /voirSortie/{id}
    defaults:  { _controller: SCActiviteBundle:Sortie:voirSortie }
    requirements:
        id: \d+ 
        
sc_activite_deleteSortie:
    path:      /deleteSortie/{id}/{dateSortie}/{lieu}
    defaults:  { _controller: SCActiviteBundle:Sortie:deleteSortie}
    requirements:
        id: \d+
        
sc_activite_addStage:
    path:      /addStage/{id}
    defaults:  { _controller: SCActiviteBundle:Stage:add }
    requirements:
        id: \d+
        
sc_activite_viewStage:
    path:      /viewStage/{id}
    defaults:  { _controller: SCActiviteBundle:Stage:view }
    requirements:
        id: \d+ 
        
sc_activite_deleteStage:
    path:      /deleteStage/{id}/{debutStage}/{finStage}
    defaults:  { _controller: SCActiviteBundle:Stage:delete}
    requirements:
        id: \d+
        debutStage: "[0-9-]+"
        finStage: "[0-9-]+"
        
sc_activite_editStage:
    path:      /editStage/{id}/{debutStage}/{finStage}
    defaults:  { _controller: SCActiviteBundle:Stage:edit}
    requirements:
        id: \d+
        debutStage: "[0-9-]+"
        finStage: "[0-9-]+"

sc_activite_inscriptionActivite:
    path:      /inscriptionActivite/{id}
    defaults:  { _controller: SCActiviteBundle:InscriptionActivite:inscriptionActivite }
    requirements:
        id: \d+
        
sc_activite_getEnfant:
    path:      /getEnfant/{id}/{dateSortie}/{lieu}
    defaults:  { _controller: SCActiviteBundle:InscriptionSortie:getEnfant }
    requirements:
        id: \d+
        
sc_activite_actionSortie:
    path:      /actionSortie/{id}/{dateSortie}/{lieu}
    defaults:  { _controller: SCActiviteBundle:Sortie:actionSortie }
    requirements:
        id: \d+    
        
sc_activite_listeEnfantsInscrits:
    path:      /monCompte/viewInscription
    defaults:  { _controller: SCActiviteBundle:InscriptionActivite:viewInscriActivite }

        
sc_activite_inscrireEnfant:
    path:      /inscrireEnfant/{id}/{userParent}/{nomEnfant}/{prenomEnfant}
    defaults:  { _controller: SCActiviteBundle:InscriptionSortie:inscrireEnfant }
    requirements:
        id: \d+          

sc_activite_personnesInscrites:
    path:      /personnesInscrites/{id}
    defaults:  { _controller: SCActiviteBundle:InscriptionSortie:inscrits }
    requirements:
        id: \d+    


sc_activite_viewChildren:
    path:      /viewChildren/{id}/{debutStage}/{finStage}
    defaults: {_controller:SCActiviteBundle:InscriptionStage:viewChildren }
    requirements:
        id: \d+
        debutStage: "[0-9-]+"
        finStage: "[0-9-]+"
        
sc_activite_viewChildrenStages:
    path:      /viewChildrenStages/{id}
    defaults:  {_controller:SCActiviteBundle:InscriptionStage:viewChildrenStages}
    requirements:
        id: \d+

sc_activite_viewAllStagesUser:
    path:      /viewAllStagesUser/{email}
    defaults:   {_controller:SCUserBundle:Admin:viewAllStagesUser}
    requirements:
        email : "[^/]+"
        
sc_activite_confirmPayment:
    path:       /confirmPayment/{id}/{email}/{nomEnfant}/{prenomEnfant}/{debutStage}/{finStage}
    defaults:   {_controller:SCActiviteBundle:InscriptionStage:confirmPayment}
    requirements:
        id: \d+
        email: "[^/]+"
        nomEnfant: "[^/]+"
        prenomEnfant: "[^/]+"
        debutStage: "[0-9-]+"
        finStage: "[0-9-]+"