# src/SC/ActiviteBundle/Resources/config/routing.yml

sc_activite_homepage:
    path:     /activite/{page}
    defaults: { _controller: SCActiviteBundle:Activite:index, page: 1 }    
    requirements:
        page: \d* 

sc_activite_view:
    path:      /activite/view/{id}
    defaults:  { _controller: SCActiviteBundle:Activite:view }
    requirements:
        id: \d+
sc_activite_add:
    path:      /admin/activite/add
    defaults:  { _controller: SCActiviteBundle:Activite:add }
sc_activite_edit:
    path:      /admin/activite/edit/{id}
    defaults:  { _controller: SCActiviteBundle:Activite:edit }
    requirements:
        id: \d+
sc_activite_delete:
    path:      /admin/activite/delete/{id}
    defaults:  { _controller: SCActiviteBundle:Activite:delete }
    requirements:
        id: \d+ 
        
sc_activite_ajoutSortie:
    path:      admin/activite/ajoutSortie/{id}
    defaults:  { _controller: SCActiviteBundle:Sortie:ajoutSortie }
    requirements:
        id: \d+
        
sc_activite_voirSortie:
    path:      /activite/voirSortie/{id}
    defaults:  { _controller: SCActiviteBundle:Sortie:voirSortie }
    requirements:
        id: \d+ 
        
sc_activite_deleteSortie:
    path:      admin/activite/deleteSortie/{id}/{dateSortie}/{lieu}
    defaults:  { _controller: SCActiviteBundle:Sortie:deleteSortie}
    requirements:
        id: \d+
        
sc_activite_addStage:
    path:      admin/activite/addStage/{id}
    defaults:  { _controller: SCActiviteBundle:Stage:add }
    requirements:
        id: \d+
        
sc_activite_viewStage:
    path:      /activite/viewStage/{id}
    defaults:  { _controller: SCActiviteBundle:Stage:view }
    requirements:
        id: \d+ 
        
sc_activite_deleteStage:
    path:      admin/activite/deleteStage/{id}/{debutStage}/{finStage}
    defaults:  { _controller: SCActiviteBundle:Stage:delete}
    requirements:
        id: \d+
        debutStage: "[0-9-]+"
        finStage: "[0-9-]+"
        
sc_activite_editStage:
    path:      admin/activite/editStage/{id}/{debutStage}/{finStage}
    defaults:  { _controller: SCActiviteBundle:Stage:edit}
    requirements:
        id: \d+
        debutStage: "[0-9-]+"
        finStage: "[0-9-]+"

sc_activite_inscriptionActivite:
    path:      /activite/inscriptionActivite/{id}
    defaults:  { _controller: SCActiviteBundle:InscriptionActivite:inscriptionActivite }
    requirements:
        id: \d+
        
sc_activite_getEnfant:
    path:      /activite/getEnfant/{id}/{dateSortie}/{lieu}
    defaults:  { _controller: SCActiviteBundle:InscriptionSortie:getEnfant }
    requirements:
        id: \d+
        
sc_activite_actionSortie:
    path:      /activite/actionSortie/{id}/{dateSortie}/{lieu}
    defaults:  { _controller: SCActiviteBundle:Sortie:actionSortie }
    requirements:
        id: \d+    
        
sc_activite_obtenirSortie:
    path:      /activite/obtenirSortie/{id}
    defaults:  { _controller: SCActiviteBundle:InscriptionSortie:obtenirSortie }
    requirements:
        id: \d+         


        
sc_activite_inscrireEnfant:
    path:      /activite/inscrireEnfant/{id}/{nomEnfant}/{prenomEnfant}
    defaults:  { _controller: SCActiviteBundle:InscriptionSortie:inscrireEnfant }
    requirements:
        id: \d+          

sc_activite_personnesInscrites:
    path:      /activite/personnesInscrites/{id}
    defaults:  { _controller: SCActiviteBundle:InscriptionSortie:inscrits }
    requirements:
        id: \d+    


sc_activite_viewChildren:
    path:      /activite/viewChildren/{id}/{debutStage}/{finStage}
    defaults: {_controller:SCActiviteBundle:InscriptionStage:viewChildren }
    requirements:
        id: \d+
        debutStage: "[0-9-]+"
        finStage: "[0-9-]+"
        
sc_activite_viewChildrenStages:
    path:      /activite/viewChildrenStages/{id}
    defaults:  {_controller:SCActiviteBundle:InscriptionStage:viewChildrenStages}
    requirements:
        id: \d+

sc_activite_viewAllStagesUser:
    path:      admin/activite/viewAllStagesUser/{email}
    defaults:   {_controller:SCUserBundle:Admin:viewAllStagesUser}
    requirements:
        email : "[^/]+"
        
sc_activite_confirmPayment:
    path:       admin/activite/confirmPayment/{id}/{email}/{nomEnfant}/{prenomEnfant}/{debutStage}/{finStage}
    defaults:   {_controller:SCActiviteBundle:InscriptionStage:confirmPayment}
    requirements:
        id: \d+
        email: "[^/]+"
        nomEnfant: "[^/]+"
        prenomEnfant: "[^/]+"
        debutStage: "[0-9-]+"
        finStage: "[0-9-]+"

sc_activite_deleteInscriptionStage:
    path:       admin/activite/deleteInscriptionStage/{id}/{email}/{nomEnfant}/{prenomEnfant}/{debutStage}/{finStage}
    defaults:   {_controller:SCActiviteBundle:InscriptionStage:deleteInscriptionStage}
    requirements:
        id: \d+
        email: "[^/]+"
        nomEnfant: "[^/]+"
        prenomEnfant: "[^/]+"
        debutStage: "[0-9-]+"
        finStage: "[0-9-]+"
        
sc_activite_editSortie:
    path:      admin/editSortie/{id}/{dateSortie}/{nomLieu}
    defaults:  { _controller: SCActiviteBundle:Sortie:editSortie}
    requirements:
        id: \d+    
